encoder-embed-dim-subtransformer: 640
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [2048, 1024, 512, 2048, 2048, 1024]
decoder-ffn-embed-dim-all-subtransformer: [512, 512, 1024, 1024, 512, 1024]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 4

encoder-self-attention-heads-all-subtransformer: [2, 4, 2, 2, 2, 4]
decoder-self-attention-heads-all-subtransformer: [2, 4, 2, 4, 4, 4]
decoder-ende-attention-heads-all-subtransformer: [4, 4, 2, 2, 4, 4]

decoder-arbitrary-ende-attn-all-subtransformer: [2, 1, 2, 1, 1, -1]

