encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 640

encoder-ffn-embed-dim-all-subtransformer: [1024, 3072, 2048, 2048, 1024, 3072]
decoder-ffn-embed-dim-all-subtransformer: [1024, 3072, 2048, 1024, 1024, 1024]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 5

encoder-self-attention-heads-all-subtransformer: [8, 4, 4, 4, 4, 8]
decoder-self-attention-heads-all-subtransformer: [8, 8, 4, 8, 4, 4]
decoder-ende-attention-heads-all-subtransformer: [4, 4, 4, 4, 4, 4]

decoder-arbitrary-ende-attn-all-subtransformer: [2, 1, -1, 2, -1, 1]

